apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: motosmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: juandamartinez/motosmart:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root123
            - name: DB_NAME
              value: motosmart