apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: motosmart-ingress
  namespace: motosmart
spec:
  rules:
    - host: motosmart.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000